// Mocks generated by Mockito 5.4.6 from annotations
// in awesome_task_manager/test/src/widgets/task_observer_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:awesome_task_manager/awesome_task_manager.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSharedResultManager_0 extends _i1.SmartFake
    implements _i2.SharedResultManager {
  _FakeSharedResultManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSequentialQueueManager_1 extends _i1.SmartFake
    implements _i2.SequentialQueueManager {
  _FakeSequentialQueueManager_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaskPoolManager_2 extends _i1.SmartFake
    implements _i2.TaskPoolManager {
  _FakeTaskPoolManager_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRejectedAfterThresholdManager_3 extends _i1.SmartFake
    implements _i2.RejectedAfterThresholdManager {
  _FakeRejectedAfterThresholdManager_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCancelPreviousTaskManager_4 extends _i1.SmartFake
    implements _i2.CancelPreviousTaskManager {
  _FakeCancelPreviousTaskManager_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AwesomeTaskManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAwesomeTaskManager extends _i1.Mock
    implements _i2.AwesomeTaskManager {
  @override
  _i3.Stream<_i2.TaskStatus<dynamic>?> getTaskStatusStream({
    String? taskId,
    String? managerId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTaskStatusStream,
          [],
          {
            #taskId: taskId,
            #managerId: managerId,
          },
        ),
        returnValue: _i3.Stream<_i2.TaskStatus<dynamic>?>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.TaskStatus<dynamic>?>.empty(),
      ) as _i3.Stream<_i2.TaskStatus<dynamic>?>);

  @override
  _i2.SharedResultManager createSharedResultManager(
          {required String? managerId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSharedResultManager,
          [],
          {#managerId: managerId},
        ),
        returnValue: _FakeSharedResultManager_0(
          this,
          Invocation.method(
            #createSharedResultManager,
            [],
            {#managerId: managerId},
          ),
        ),
        returnValueForMissingStub: _FakeSharedResultManager_0(
          this,
          Invocation.method(
            #createSharedResultManager,
            [],
            {#managerId: managerId},
          ),
        ),
      ) as _i2.SharedResultManager);

  @override
  _i2.SequentialQueueManager createSequentialQueueManager(
          {required String? managerId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSequentialQueueManager,
          [],
          {#managerId: managerId},
        ),
        returnValue: _FakeSequentialQueueManager_1(
          this,
          Invocation.method(
            #createSequentialQueueManager,
            [],
            {#managerId: managerId},
          ),
        ),
        returnValueForMissingStub: _FakeSequentialQueueManager_1(
          this,
          Invocation.method(
            #createSequentialQueueManager,
            [],
            {#managerId: managerId},
          ),
        ),
      ) as _i2.SequentialQueueManager);

  @override
  _i2.TaskPoolManager createTaskPoolManager({
    required String? managerId,
    int? poolSize = 2,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTaskPoolManager,
          [],
          {
            #managerId: managerId,
            #poolSize: poolSize,
          },
        ),
        returnValue: _FakeTaskPoolManager_2(
          this,
          Invocation.method(
            #createTaskPoolManager,
            [],
            {
              #managerId: managerId,
              #poolSize: poolSize,
            },
          ),
        ),
        returnValueForMissingStub: _FakeTaskPoolManager_2(
          this,
          Invocation.method(
            #createTaskPoolManager,
            [],
            {
              #managerId: managerId,
              #poolSize: poolSize,
            },
          ),
        ),
      ) as _i2.TaskPoolManager);

  @override
  _i2.RejectedAfterThresholdManager createRejectedAfterThresholdManager({
    required String? managerId,
    int? taskThreshold = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRejectedAfterThresholdManager,
          [],
          {
            #managerId: managerId,
            #taskThreshold: taskThreshold,
          },
        ),
        returnValue: _FakeRejectedAfterThresholdManager_3(
          this,
          Invocation.method(
            #createRejectedAfterThresholdManager,
            [],
            {
              #managerId: managerId,
              #taskThreshold: taskThreshold,
            },
          ),
        ),
        returnValueForMissingStub: _FakeRejectedAfterThresholdManager_3(
          this,
          Invocation.method(
            #createRejectedAfterThresholdManager,
            [],
            {
              #managerId: managerId,
              #taskThreshold: taskThreshold,
            },
          ),
        ),
      ) as _i2.RejectedAfterThresholdManager);

  @override
  _i2.CancelPreviousTaskManager createCancelPreviousTaskManager({
    required String? managerId,
    int? maximumParallelTasks = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCancelPreviousTaskManager,
          [],
          {
            #managerId: managerId,
            #maximumParallelTasks: maximumParallelTasks,
          },
        ),
        returnValue: _FakeCancelPreviousTaskManager_4(
          this,
          Invocation.method(
            #createCancelPreviousTaskManager,
            [],
            {
              #managerId: managerId,
              #maximumParallelTasks: maximumParallelTasks,
            },
          ),
        ),
        returnValueForMissingStub: _FakeCancelPreviousTaskManager_4(
          this,
          Invocation.method(
            #createCancelPreviousTaskManager,
            [],
            {
              #managerId: managerId,
              #maximumParallelTasks: maximumParallelTasks,
            },
          ),
        ),
      ) as _i2.CancelPreviousTaskManager);

  @override
  void registerLogListener(_i2.LogListener? listener) => super.noSuchMethod(
        Invocation.method(
          #registerLogListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterLogListener(_i2.LogListener? listener) => super.noSuchMethod(
        Invocation.method(
          #unregisterLogListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void log(
    String? message, {
    DateTime? time,
    int? sequenceNumber,
    int? level = 0,
    String? name = '',
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [message],
          {
            #time: time,
            #sequenceNumber: sequenceNumber,
            #level: level,
            #name: name,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );
}
