// Mocks generated by Mockito 5.4.4 from annotations
// in awesome_task_manager/test/src/resolvers/task_resolver_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:awesome_task_manager/awesome_task_manager.dart' as _i3;
import 'package:awesome_task_manager/src/tasks/cancelable_task.dart' as _i4;
import 'package:awesome_task_manager/src/types/types.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompleter_2<T1> extends _i1.SmartFake implements _i2.Completer<T1> {
  _FakeCompleter_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaskStatus_3<T1> extends _i1.SmartFake
    implements _i3.TaskStatus<T1> {
  _FakeTaskStatus_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Stopwatch].
///
/// See the documentation for Mockito's code generation for more information.
class MockStopwatch extends _i1.Mock implements Stopwatch {
  @override
  int get frequency => (super.noSuchMethod(
        Invocation.getter(#frequency),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get elapsedTicks => (super.noSuchMethod(
        Invocation.getter(#elapsedTicks),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  Duration get elapsed => (super.noSuchMethod(
        Invocation.getter(#elapsed),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#elapsed),
        ),
        returnValueForMissingStub: _FakeDuration_0(
          this,
          Invocation.getter(#elapsed),
        ),
      ) as Duration);

  @override
  int get elapsedMicroseconds => (super.noSuchMethod(
        Invocation.getter(#elapsedMicroseconds),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get elapsedMilliseconds => (super.noSuchMethod(
        Invocation.getter(#elapsedMilliseconds),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get isRunning => (super.noSuchMethod(
        Invocation.getter(#isRunning),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void start() => super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stop() => super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CancelableTask].
///
/// See the documentation for Mockito's code generation for more information.
class MockCancelableTask<T> extends _i1.Mock implements _i4.CancelableTask<T> {
  @override
  _i5.Task<T> get task => (super.noSuchMethod(
        Invocation.getter(#task),
        returnValue: (_i3.TaskStatus<dynamic> status) =>
            _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.getter(#task),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.getter(#task),
            ),
        returnValueForMissingStub: (_i3.TaskStatus<dynamic> status) =>
            _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.getter(#task),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.getter(#task),
            ),
      ) as _i5.Task<T>);

  @override
  String get taskId => (super.noSuchMethod(
        Invocation.getter(#taskId),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#taskId),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#taskId),
        ),
      ) as String);

  @override
  _i2.Completer<T> get completer => (super.noSuchMethod(
        Invocation.getter(#completer),
        returnValue: _FakeCompleter_2<T>(
          this,
          Invocation.getter(#completer),
        ),
        returnValueForMissingStub: _FakeCompleter_2<T>(
          this,
          Invocation.getter(#completer),
        ),
      ) as _i2.Completer<T>);

  @override
  void Function(
    String, {
    Object? error,
    int level,
    String name,
    int? sequenceNumber,
    StackTrace? stackTrace,
    DateTime? time,
    _i2.Zone? zone,
  }) get customDevLog => (super.noSuchMethod(
        Invocation.getter(#customDevLog),
        returnValue: (
          String message, {
          Object? error,
          int? level,
          String? name,
          int? sequenceNumber,
          StackTrace? stackTrace,
          DateTime? time,
          _i2.Zone? zone,
        }) {},
        returnValueForMissingStub: (
          String message, {
          Object? error,
          int? level,
          String? name,
          int? sequenceNumber,
          StackTrace? stackTrace,
          DateTime? time,
          _i2.Zone? zone,
        }) {},
      ) as void Function(
        String, {
        Object? error,
        int level,
        String name,
        int? sequenceNumber,
        StackTrace? stackTrace,
        DateTime? time,
        _i2.Zone? zone,
      }));

  @override
  _i3.TaskStatus<T> get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _FakeTaskStatus_3<T>(
          this,
          Invocation.getter(#status),
        ),
        returnValueForMissingStub: _FakeTaskStatus_3<T>(
          this,
          Invocation.getter(#status),
        ),
      ) as _i3.TaskStatus<T>);

  @override
  set status(_i3.TaskStatus<T>? _status) => super.noSuchMethod(
        Invocation.setter(
          #status,
          _status,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Future<T> get future => (super.noSuchMethod(
        Invocation.getter(#future),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.getter(#future),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.getter(#future),
            ),
        returnValueForMissingStub: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.getter(#future),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.getter(#future),
            ),
      ) as _i2.Future<T>);

  @override
  bool get isCanceled => (super.noSuchMethod(
        Invocation.getter(#isCanceled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isTimedOut => (super.noSuchMethod(
        Invocation.getter(#isTimedOut),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get executed => (super.noSuchMethod(
        Invocation.getter(#executed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isExecuting => (super.noSuchMethod(
        Invocation.getter(#isExecuting),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isError => (super.noSuchMethod(
        Invocation.getter(#isError),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isCompleted => (super.noSuchMethod(
        Invocation.getter(#isCompleted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set isError(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isError,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set executed(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #executed,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isTimedOut(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isTimedOut,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isCanceled(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isCanceled,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool cancel() => (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.Future<T> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #execute,
                  [],
                ),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #execute,
                [],
              ),
            ),
        returnValueForMissingStub: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #execute,
                  [],
                ),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #execute,
                [],
              ),
            ),
      ) as _i2.Future<T>);

  @override
  _i2.FutureOr<dynamic> onNewResult(T? lastValue) => (super.noSuchMethod(
        Invocation.method(
          #onNewResult,
          [lastValue],
        ),
        returnValueForMissingStub: null,
      ) as _i2.FutureOr<dynamic>);

  @override
  void emitNewState() => super.noSuchMethod(
        Invocation.method(
          #emitNewState,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
